apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
    name: jumpcapstone
=======
    name: jumpcaptone
>>>>>>> deployment
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
<<<<<<< HEAD
        app: jumpcapstone
=======
        app: jumpcaptone
>>>>>>> deployment
